/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package teenpatti;

import java.awt.Image;
import java.util.Random;
import javax.swing.ImageIcon;

/**
 *
 * @author disha
 */
public class Layout extends javax.swing.JFrame {

    /**
     * Creates new form Layout
     */
    public Layout() {
        initComponents();
        /*ImageIcon imageicon = new ImageIcon(new ImageIcon("index.jpg").getImage().getScaledInstance(jLabel1.getWidth(),jLabel1.getHeight(),Image.SCALE_DEFAULT));
        
         jLabel1.setBounds(50, 50,JFrame.WIDTH,JFrame.HEIGHT);
         jLabel1.setIcon(imageicon);*/
        ImageIcon img1 = new ImageIcon(new ImageIcon("table1.png").getImage().getScaledInstance(this.getWidth(), this.getHeight(), Image.SCALE_DEFAULT));
        jLabel1.setIcon(img1);
        ImageIcon imageicon1 = new ImageIcon(new ImageIcon("backd.png").getImage().getScaledInstance(35, 50, Image.SCALE_DEFAULT));
        jLabel7.setIcon(imageicon1);
        jLabel8.setIcon(imageicon1);
        jLabel9.setIcon(imageicon1);

        int ran1, ran2, ran3;
        ran1 = random();

        String img = String.format("ace%d.png", ran1);
        ImageIcon imageicon = new ImageIcon(new ImageIcon(img).getImage().getScaledInstance(50, 65, Image.SCALE_DEFAULT));

        jLabel3.setIcon(imageicon);

        do {
            ran2 = random();
        } while (ran2 == ran1);
        String img2 = String.format("ace%d.png", ran2);
        ImageIcon imageicon2 = new ImageIcon(new ImageIcon(img2).getImage().getScaledInstance(50, 65, Image.SCALE_DEFAULT));
        jLabel4.setIcon(imageicon2);

        do {
            ran3 = random();
        } while (ran3 == ran1 && ran3 == ran2);
        jLabel11.setText(ran3 + "");
        String img3 = String.format("ace%d.png", ran3);
        ImageIcon imageicon3 = new ImageIcon(new ImageIcon(img3).getImage().getScaledInstance(50, 65, Image.SCALE_DEFAULT));
        jLabel5.setIcon(imageicon3);
//        setLayout(new GridLayout(1, 2));
//        try {
//            BufferedImage original = ImageIO.read(new File("F:\\study\\sem-4\\java\\TeenPatti\\cards\\1_2.png"));
//            BufferedImage skew = new BufferedImage(original.getWidth(), original.getHeight(), BufferedImage.TYPE_INT_ARGB);
//
//            // Adjust the image width if we use a negative skew...
//            double skewX = 0.3d;
//            double x = (skewX < 0) ? -skewX * original.getHeight() : 0;
//            AffineTransform at = AffineTransform.getTranslateInstance(x, 0);
//            at.shear(skewX, 0);
//            AffineTransformOp op = new AffineTransformOp(at,
//                    new RenderingHints(RenderingHints.KEY_INTERPOLATION,
//                            RenderingHints.VALUE_INTERPOLATION_BICUBIC));
//            skew = op.filter(original, null);
//
//            jLabel12.add(new JLabel(new ImageIcon(original)));
//            jLabel12.add(new JLabel(new ImageIcon(skew)));
//        } catch (Exception e) {
//            e.printStackTrace();
//        }
//        int drawLocationX = 300;
//int drawLocationY = 300;
//        Graphics2D g2d;
//// Rotation information
//ImageIcon image = new ImageIcon(new ImageIcon("1_1.png").getImage());
//double rotationRequired = Math.toRadians (45);
//double locationX = image.getIconWidth() / 2;
//double locationY = image.getIconHeight() / 2;
//AffineTransform tx = AffineTransform.getRotateInstance(rotationRequired, locationX, locationY);
//AffineTransformOp op = new AffineTransformOp(tx, AffineTransformOp.TYPE_BILINEAR);
//
//// Drawing the rotated image at the required drawing locations
//
//g2d.drawImage(op.filter(image, null), drawLocationX, drawLocationY, null);
//g2d.drawImage(image, drawLocationX, drawLocationY, null);

    }

    public static int random() {
        Random r = new Random();
        int ran = (r.nextInt(3) + 1);

        return ran;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        panel1 = new java.awt.Panel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();

        jLabel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 204));
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                formComponentResized(evt);
            }
        });

        panel1.setMinimumSize(new java.awt.Dimension(798, 468));
        panel1.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                panel1ComponentResized(evt);
            }
        });
        panel1.setLayout(null);

        jLabel2.setText("jLabel2");
        panel1.add(jLabel2);
        jLabel2.setBounds(350, 380, 80, 80);

        jLabel3.setText("jLabel3");
        panel1.add(jLabel3);
        jLabel3.setBounds(320, 290, 50, 70);

        jLabel4.setText("jLabel4");
        panel1.add(jLabel4);
        jLabel4.setBounds(380, 290, 50, 70);

        jLabel5.setText("jLabel5");
        panel1.add(jLabel5);
        jLabel5.setBounds(440, 290, 50, 70);

        jLabel6.setText("jLabel6");
        panel1.add(jLabel6);
        jLabel6.setBounds(360, 10, 70, 80);

        jLabel7.setText("jLabel7");
        panel1.add(jLabel7);
        jLabel7.setBounds(350, 130, 35, 50);

        jLabel8.setText("jLabel8");
        panel1.add(jLabel8);
        jLabel8.setBounds(380, 130, 34, 50);

        jLabel9.setText("jLabel9");
        panel1.add(jLabel9);
        jLabel9.setBounds(410, 130, 34, 50);

        jButton1.setBackground(new java.awt.Color(204, 0, 0));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Pack");
        panel1.add(jButton1);
        jButton1.setBounds(450, 380, 70, 40);

        jButton2.setText("Show");
        jButton2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        panel1.add(jButton2);
        jButton2.setBounds(450, 440, 50, 21);

        jButton3.setText("+");
        jButton3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panel1.add(jButton3);
        jButton3.setBounds(270, 380, 30, 21);

        jButton4.setText("-");
        jButton4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panel1.add(jButton4);
        jButton4.setBounds(270, 440, 30, 21);

        jLabel10.setText("jLabel10");
        panel1.add(jLabel10);
        jLabel10.setBounds(270, 410, 70, 20);

        jLabel11.setText("jLabel11");
        panel1.add(jLabel11);
        jLabel11.setBounds(320, 210, 180, 50);

        jLabel12.setText("jLabel12");
        panel1.add(jLabel12);
        jLabel12.setBounds(40, 20, 200, 160);

        jLabel14.setIcon(new javax.swing.ImageIcon("C:\\Users\\disha\\Desktop\\Teen Patti\\pack.png")); // NOI18N
        panel1.add(jLabel14);
        jLabel14.setBounds(580, 390, 73, 50);

        jLabel13.setIcon(new javax.swing.ImageIcon("C:\\Users\\disha\\Desktop\\Teen Patti\\d.png")); // NOI18N
        panel1.add(jLabel13);
        jLabel13.setBounds(630, 290, 90, 50);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 468, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void panel1ComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_panel1ComponentResized
        // TODO add your handling code here:
        //panel1.setSize(this.getSize());

    }//GEN-LAST:event_panel1ComponentResized

    private void formComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentResized
        // TODO add your handling code here:
        panel1.setSize(this.getSize());
        //jLabel1.setSize(panel1.WIDTH,panel1.HEIGHT);
        ImageIcon img1 = new ImageIcon(new ImageIcon("table1.png").getImage().getScaledInstance(this.getWidth(), this.getHeight(), Image.SCALE_DEFAULT));
        jLabel1.setIcon(img1);
    }//GEN-LAST:event_formComponentResized

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Layout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Layout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Layout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Layout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Layout().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private java.awt.Panel panel1;
    // End of variables declaration//GEN-END:variables
}
